In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [6]:
np.exp(arr) #takes e^array element

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [8]:
A = np.random.randn(10)
A

array([ 0.07721086, -0.70604498,  0.05229487,  1.84012914, -0.57982812,
        0.49171731, -1.57219568,  0.70421761, -0.92092321, -1.23944704])

In [11]:
B = np.random.randn(10)
B

array([-0.07728224, -0.83647454, -0.45132993, -1.25744446, -2.27524803,
       -0.61598296,  0.37042355,  1.16651563, -1.57630424,  0.90581338])

In [12]:
np.add(A,B)

array([-7.13835366e-05, -1.54251952e+00, -3.99035061e-01,  5.82684677e-01,
       -2.85507616e+00, -1.24265647e-01, -1.20177213e+00,  1.87073325e+00,
       -2.49722745e+00, -3.33633665e-01])

In [13]:
np.maximum(A,B)

array([ 0.07721086, -0.70604498,  0.05229487,  1.84012914, -0.57982812,
        0.49171731,  0.37042355,  1.16651563, -0.92092321,  0.90581338])

In [14]:
website = "google.com"
import webbrowser
webbrowser.open(website)


True