In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[2]

2

In [7]:
arr[1:5] #slicing is not inclusive of the last value

array([1, 2, 3, 4])

In [8]:
arr[8:]

array([ 8,  9, 10])

In [9]:
arr[0:3] = 21

In [10]:
arr

array([21, 21, 21,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr = np.arange(0,11)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
slice_of_arr = arr[0:6]

In [14]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [15]:
slice_of_arr[:] = 99

In [16]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [17]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

#### slicing array affects original array when extracted, unless you copy()

In [19]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [21]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [22]:
arr_2d[2]

array([35, 40, 45])

In [24]:
arr_2d[1][1]

25

In [25]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [26]:
arr_2d[:2,:1]

array([[ 5],
       [20]])

In [27]:
arr2d = np.zeros((10,10))

In [28]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
arr_length = arr2d.shape[1]

In [30]:
arr_length

10

In [33]:
for i in range(arr_length):
    arr2d[i]=1

In [34]:
arr2d

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])