In [1]:
import numpy as np

In [2]:
my_list1 = [1,2,3,4,5]

In [9]:
my_array1 = np.array(my_list1)

#### TURNED LIST INTO AN ARRAY

In [4]:
my_array1

array([1, 2, 3, 4, 5])

In [5]:
my_list2 = [11,22,33,44,55]

In [6]:
my_lists = [my_list1,my_list2]

#### MULTIDIMENSIONAL LIST INTO AN ARRAY

In [7]:
my_array2 = np.array(my_lists)

In [11]:
my_array2

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [13]:
my_array2.shape

(2, 5)

### shows row by column

In [14]:
my_array2.dtype

dtype('int32')

In [19]:
my_zeros = np.zeros([3,3]) 

### np.zeros gives a matrix of zeros

In [18]:
my_zeros.dtype

dtype('float64')

In [20]:
my_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

###### also ones

In [21]:
my_ones = np.ones([5,5])

In [22]:
my_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### create an array of ones

In [24]:
my_identity = np.eye(3) #specify order only, cannot enter list [3,3]

In [25]:
my_identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##### create an identity matrix

In [26]:
my_unique = np.arange(1,21)

In [27]:
my_unique

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

##### arrays can be created using a-range funfction by indicating a start,stop and count