In [1]:
import numpy as np

In [2]:
5/2

2.5

In [4]:
array1 = np.array([[1,2,3,4],[8,9,10,11]])

In [5]:
array1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [6]:
array1*array1


array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [7]:
array1+array1

array([[ 2,  4,  6,  8],
       [16, 18, 20, 22]])

In [8]:
1/array1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [9]:
array1**3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]], dtype=int32)

In [10]:
np?

Type:        module
String form: <module 'numpy' from 'C:\\Users\\serna\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\serna\appdata\local\programs\python\python39\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are